### ISSUE TITLE
contains project

### ISSUE THREAD

**Issue by susanlovaglio** [learn-co-curriculum/swift-uiElements-readme#5]
student is asked to create a new project and it already contains one.

**Comment by JimCampagno** [comment]
Under one of the top headers is the following:

> To begin this investigation, create a new iOS project in Xcode. You can use the single-view application template provided with Xcode. (There is also a sample application included in this repository. It's located at UIElements/UIElements.xcodeproj. But you should start your own project so you can get a feel for these elements yourself.)

Have you seen that students are confused that there is a project included? If so, I will remove that sentence and the project as well. Thoughts?

@susanlovaglio

**Comment by susanlovaglio** [comment]
Yea, last semester and this one students talk about there being files in the folders. They're going straight to the clone instead of reading the instructions first.

**Comment by JimCampagno** [comment]
Sounds good. I removed the Xcode project and that part of the instructions that state that there _is_ an Xcode project available to the students.

@susanlovaglio
